# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: charmed-hpc-terraform tests
on:
  workflow_call:
  pull_request:

jobs:
  inclusive-naming-check:
    name: Inclusive naming check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true

  validation-test:
    name: Validation tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install `opentofu`
        run: sudo snap install opentofu --classic
      - name: Install `just`
        uses: extractions/setup-just@v2
        with:
          just-version: 1.38.0
      - name: Run validation tests
        run: just validate
